"""Constants for the Bluetti BT integration."""

from typing import Literal

from bluetti_bt_lib import FieldName

from homeassistant.const import EntityCategory

DOMAIN = "bluetti_bt"

CONF_ENCRYPTION = "encryption"
CONF_SERIAL = "serial"

type DetailName = Literal["unit", "category", "device_class", "state_class"]
type EntityDetails = dict[DetailName, str]
type EntityDetailsMap = dict[FieldName, EntityDetails]

ENTITY_DETAILS_MAPPING: EntityDetailsMap = {
    FieldName.AC_1_O_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_ECO_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_ECO_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_I_F: {
        "unit": "Hz",
        "category": None,
        "device_class": "frequency",
        "state_class": "measurement",
    },
    FieldName.AC_1_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_I_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_O_F: {
        "unit": "Hz",
        "category": None,
        "device_class": "frequency",
        "state_class": None,
    },
    FieldName.AC_O_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_O_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_O_SWITCH: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_POWER_LIFTING_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_UPS_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_HIGH: {
        "unit": "%",
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_LOW: {
        "unit": "%",
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_TOTAL: {
        "unit": "%",
        "category": None,
        "device_class": "battery",
        "state_class": "measurement",
    },
    FieldName.D_CHARGING_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_DISPLAY_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_INVERTER_TYPE: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_LED_MODE: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_POWER_OFF: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_SERIAL: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_SPLIT_PHASE_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_SPLIT_PHASE_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_VER_ARM: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_VER_DSP: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.DC_I_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.DC_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.DC_O_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.DC_O_SWITCH: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.PV_1_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_1_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_1_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_I_E_TOTAL: {
        "unit": "kWh",
        "category": None,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    FieldName.AC_1_O_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_1_O_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_1_O_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_2_O_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_2_O_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_2_O_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_3_O_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_3_O_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_3_O_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_ECO_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_ECO_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_I_F: {
        "unit": "Hz",
        "category": None,
        "device_class": "frequency",
        "state_class": "measurement",
    },
    FieldName.AC_1_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_1_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_1_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_2_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_2_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_2_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_3_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.AC_3_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_3_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.AC_I_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_O_F: {
        "unit": "Hz",
        "category": None,
        "device_class": "frequency",
        "state_class": None,
    },
    FieldName.AC_O_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.AC_O_SWITCH: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.AC_POWER_LIFTING_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_HIGH: {
        "unit": "%",
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_LOW: {
        "unit": "%",
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_SOC_TOTAL: {
        "unit": "%",
        "category": None,
        "device_class": "battery",
        "state_class": "measurement",
    },
    FieldName.B_TYPE: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.B_VER_BMS: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_CHARGING_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_DISPLAY_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_INVERTER_TYPE: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_SERIAL: {
        "unit": None,
        "category": EntityCategory.DIAGNOSTIC,
        "device_class": None,
        "state_class": None,
    },
    FieldName.D_TIME_REMAINING: {
        "unit": None,
        "category": None,
        "device_class": "duration",
        "state_class": None,
    },
    FieldName.DC_ECO_MODE: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.DC_ECO_SWITCH: {
        "unit": None,
        "category": EntityCategory.CONFIG,
        "device_class": None,
        "state_class": None,
    },
    FieldName.DC_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.DC_I_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.DC_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.DC_O_P_TOTAL: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.DC_O_SWITCH: {
        "unit": None,
        "category": None,
        "device_class": None,
        "state_class": None,
    },
    FieldName.G_I_F: {
        "unit": "Hz",
        "category": None,
        "device_class": "frequency",
        "state_class": "measurement",
    },
    FieldName.PV_1_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_1_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_1_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_2_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_2_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_2_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_3_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_3_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_3_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_4_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_4_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_4_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_5_I_C: {
        "unit": "A",
        "category": None,
        "device_class": "current",
        "state_class": "measurement",
    },
    FieldName.PV_5_I_P: {
        "unit": "W",
        "category": None,
        "device_class": "power",
        "state_class": "measurement",
    },
    FieldName.PV_5_I_V: {
        "unit": "V",
        "category": None,
        "device_class": "voltage",
        "state_class": "measurement",
    },
    FieldName.PV_I_E_TOTAL: {
        "unit": "kWh",
        "category": None,
        "device_class": "energy",
        "state_class": "total_increasing",
    },
}
